# ----------- CONFIGURABLE START -----------
title: "Archive"
description: "Such theme, very cool."
url: https://hosoyukired.github.io # Site url, without a slash at the end.
signoff: "hosoyukired" # Your name

links:
  - name: list
    url: /
    external: false
  - name: introduce
    url: /introduce
    external: false
# ------------ CONFIGURABLE END ------------

permalink: /posts/:year/:month/:day/:title
defaults:
  - values:
      layout: "default"
